task2_1_1
vovademarnsu/OOP pull request #5
Opened 2022-02-17 16:19 UTC by vovademarnsu

2022-02-21 08:39 UTC, alradish requested changes
- Больше тестов
- Бенчмарки

2022-03-10 10:46 UTC, alradish requested changes
Нет параллельной работы. Так как вы сдали лабу почти вовремя, а я проверяю её очень поздно, то можете исправить её к следующей неделе и я зачту.

2022-03-17 07:14 UTC, alradish requested changes

2022-03-21 19:05 UTC, alradish requested changes
В тестах всё ещё ошибка

2022-03-22 17:42 UTC, alradish requested changes

2022-04-12 00:47 UTC, Leidenn2509 approved these changes

2022-04-12 00:47 UTC, Leidenn2509 commented on task2_1_1/src/main/java/ru/nsu/medvedev/v/PrimeSearch.java
> +        Searcher searcher = new Searcher();
Кажется, что переменная нигде не используется

2022-04-12 00:47 UTC, merged