Task2_3_1
vovademarnsu/OOP pull request #7
Opened 2022-04-11 18:31 UTC by vovademarnsu

2022-04-19 09:28 UTC, Leidenn2509 requested changes

2022-04-19 09:28 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Field.java
> +    private final int SQUARE_SIZE;
Модель должна быть отдельно от FX

2022-04-19 09:28 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +    Field field = new Field();
модификаторы

2022-04-20 02:24 UTC, vovademarnsu commented
Здравствуйте, Александр Владимирович, у меня произошла заминка с пр. Я думал, что сдал вовремя, но тк я начинал делать задачку на линухе, а потом переключился на винду, то произошло какое-то недопонимание с моей стороны с коммитами. Вот только сейчас заметил что не уложился по времени. Можете, пожалуйста зачесть мягкий дедлайн👉👈(дальше буду продолжать делать на винде, тк линух отказывается нормально билдить проект со змейкой и собирается каждый раз по 5 мин).

2022-04-30 06:56 UTC, Leidenn2509 requested changes

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +    Field field = new Field();
Модификаторы

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +        Point snakeHead;
Кажется, это ненужно

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +            snakeBody.add(new Point(5, field.getROWS() / 2));
Будет три точки в одной клетке?

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +    }
модификаторы

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +        }
`boolean isGameOver()`

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Food.java
> +    private Image foodImage;
Модель не должна зависить от графики. Если вдруг вы решите сделать змейку в консоли, то картика будет не нужна

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Food.java
> +    Snake snake = new Snake();
Почему еда хранит змейку?

2022-04-30 06:56 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Food.java
> +                    continue start;
Здесь явно можно обойтись без бесконечного цикла и меток (такой код тяжеловато читать). Например, я бы сделал счётчик `foodGenerated` и ходил бы в цикле пока `foodGenerated < foodNeeded`. Как вариант. Переписать этот цикл можно множеством способов

2022-05-05 06:46 UTC, Leidenn2509 requested changes
Добавить препятствия
Настройки

2022-05-05 06:46 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/Snake.java
> +    Field field = new Field();
private

2022-05-12 05:54 UTC, Leidenn2509 requested changes
пакеты
передвижение

2022-05-12 09:47 UTC, vovademarnsu commented
изменил перемещение змейки, а вот с пакетами до конца не вышло. Когда я создавал доп пакет для графики, то лоадер не мог найти fxml файл и постоянно вылетала ошибка. Пытался указывать путь до файла с разных глубин проекта, но это тоже не помогло :/

2022-05-16 15:00 UTC, Leidenn2509 requested changes
+ тесты

2022-05-18 12:21 UTC, Leidenn2509 requested changes

2022-05-18 12:21 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/model/BarrierGenerator.java
>          for (int i = 0; i < amount; i++) {
Лишний цикл

2022-05-18 12:21 UTC, Leidenn2509 commented on task3_2/src/main/java/nsu/medvedev/v/snake/model/Snake.java
> +        Point snakeHead;
Зачем?

2022-05-19 06:19 UTC, Leidenn2509 approved these changes

2022-05-19 06:19 UTC, merged